### ISSUE TITLE
Focal loss for interaction classification

### ISSUE THREAD

**Issue by xyc0833** [OreoChocolate/MUREN#7]
![image](https://github.com/OreoChocolate/MUREN/assets/57979311/c860cf43-31be-4123-8088-3cab45e2c076)
Thank you very much for your work. According to your model diagram, Human loss corresponds to the yellow box and object loss corresponds to the red box. Then how is this interaction loss designed? I see that you use Focal loss for interaction classification in your paper. I would like to know where the code of this Focal loss part is implemented in github. thank you.

**Comment by OreoChocolate** [comment]
Thank you for your interest in our research.

You can find our implementation at https://github.com/OreoChocolate/MUREN/blob/d7c8e63fad33eb0bd846dd36b3a8dbe536d8a39b/models/hoi.py#L168
