### ISSUE TITLE
category_id

### ISSUE THREAD

**Issue by anjugopinath** [OreoChocolate/MUREN#8]
Hi,

Why are there two sets of category ids as shown in the red and blue boxes? From where can I get what this category id maps to?

<img width="1075" alt="image" src="https://github.com/OreoChocolate/MUREN/assets/4654298/96e040fc-d71c-4dcb-bb9c-7785192712be">

Thank You.

**Comment by edugzlez** [comment]
I've the same problem. @OreoChocolate

**Comment by edugzlez** [comment]
``category_id`` is the category of the COCO dataset

https://github.com/amikelive/coco-labels/blob/master/coco-labels-paper.txt

**Comment by OreoChocolate** [comment]
First of all, thank you for your interest in our research.

In response, our code is built upon the codebase of CDN (Zhang et al., NeurIPS 2021), so we are using the annotations utilized in CDN.
If you visit the CDN GitHub page, you can see that they convert the annotations (i.e., category_id) from HICO-DET and V-COCO into the format proposed by PPDM (Liao et al., CVPR 2020).

Additionally, we are sharing the reference list for annotation index through the following link:
https://gist.github.com/OreoChocolate/85721bcadf943f54c3432369a1ccf414

The object index for V-COCO is the same as the object index for HICO-DET.

Thank you.

**Comment by anjugopinath** [comment]
@edugzlez and @OreoChocolate ,
Thank You for your response. This clarifies my doubt.
I was confused earlier, since I was referring the mappings given on the HICO-DET website:

[https://websites.umich.edu/~ywchao/hico/](https://websites.umich.edu/~ywchao/hico/)

<img width="95" alt="image" src="https://github.com/OreoChocolate/MUREN/assets/4654298/24210d57-7180-4191-a441-6a2c7f035f5c">

but the ids did not add up when I checked one of the images in HICO-DET and the corresponding annotations.
